### ISSUE TITLE
Cannot call value of non-function type 'UIColor'

### ISSUE THREAD

**Issue by sreckovic** [sleeve/ios-empty-application-xcode-template#1]
I get this error, it auto suggest to `window?.backgroundColor = UIColor.lightGray`after that it compile, is it possible to remove this from default template? I use xCode 8.2.1, thanks!

**Comment by sleeve** [comment]
Sorry, I missed seeing this when you filed it. It was fixed shortly after though in   https://github.com/sleeve/ios-empty-application-xcode-template/commit/a4e4c58e55326926f1c5cacd2f63840e90d8a35e.

Thanks for the report!
