### ISSUE TITLE
Does not work with Xcode 9.3

### ISSUE THREAD

**Issue by wjmelements** [sleeve/ios-empty-application-xcode-template#2]
Even after restarting Xcode, it still did not pick up the template.

```
$ ls -l ~/Library/Developer/Xcode/Templates/Application/Empty\ Application.xctemplate/
total 24
-rw-r--r--  1 will  staff  1648 Apr 10 16:54 TemplateIcon.png
-rw-r--r--  1 will  staff  2355 Apr 10 16:54 TemplateIcon@2x.png
-rwxr-xr-x  1 will  staff  2084 Apr 10 16:54 TemplateInfo.plist
```

**Comment by wjmelements** [comment]
It was not working because I had deleted the other templates, and for whatever reason that prevented this template from showing.

**Comment by sleeve** [comment]
@wjmelements Hmm, interesting. That `Application` directory is usually empty unless you have added other third custom templates in there. I'm not sure how you were able to delete the other built in templates if I'm understanding you correctly. I was unable to reproduce the behavior you saw but thanks for the report!
